CREATE DATABASE PIZZAHUT;
USE PIZZAHUT;
CREATE TABLE ORDERS(ORDER_ID INT NOT NULL,ORDER_DATE DATE NOT NULL,ORDER_TIME TIME NOT NULL, PRIMARY KEY(ORDER_ID));

CREATE TABLE ORDER_DETAILS(ORDER_DETAILS_ID INT NOT NULL,ORDER_ID INT NOT NULL,PIZZA_ID TEXT NOT NULL,QUANTITY INT NOT NULL, PRIMARY KEY(ORDER_DETAILS_ID));

SELECT * FROM PIZZAS;
SELECT * FROM PIZZA_TYPES;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;