-- BASIC:
use pizzahut;
-- 1.Retrieve the total number of orders placed.
SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS;

-- 2.Calculate the total revenue generated from pizza sales.
SELECT  ROUND(SUM(QUANTITY * PRICE),2) AS  TOTAL_SALES FROM ORDER_DETAILS JOIN PIZZAS ON PIZZAS.PIZZA_ID=ORDER_DETAILS.PIZZA_ID;

-- 3.Identify the highest-priced pizza.
SELECT PIZZA_TYPES.NAME , PIZZAS.PRICE FROM PIZZAS JOIN PIZZA_TYPES ON  PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID ORDER BY PRICE DESC LIMIT 1;

-- SELECT MAX(PRICE) FROM PIZZAS ;


-- 4.Identify the most common pizza size ordered.
SELECT QUANTITY,COUNT(ORDER_DETAILS_ID) FROM ORDER_DETAILS GROUP BY QUANTITY; -- GIVE NO OF QuaNTITY ORDERED.

SELECT PIZZAS.SIZE,COUNT(ORDER_DETAILS.ORDER_DETAILS_ID) AS 'ORDER_COUNT' FROM PIZZAS JOIN ORDER_DETAILS
ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID GROUP BY PIZZAS.SIZE ORDER BY ORDER_COUNT DESC;

-- 5.List the top 5 most ordered pizza types along with their quantities.
SELECT PIZZA_TYPES.NAME,SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY FROM PIZZA_TYPES
JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID=PIZZAS.PIZZA_TYPE_ID 
JOIN ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID=PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME ORDER BY QUANTITY DESC LIMIT 5;
